"""empty message

Revision ID: 5dd732d7a6ee
Revises: fe2e843630a8
Create Date: 2023-05-14 18:03:44.311775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd732d7a6ee'
down_revision = 'fe2e843630a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_column('current_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_day', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
