"""empty message

Revision ID: 69c4f1c6cdda
Revises: 6e84cd3d048a
Create Date: 2023-05-05 18:47:12.838824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c4f1c6cdda'
down_revision = '6e84cd3d048a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('type_upload', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    # ### end Alembic commands ###
