"""empty message

Revision ID: 80f3e801d9cd
Revises: 73ab6304e68f
Create Date: 2023-04-25 00:44:29.513128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f3e801d9cd'
down_revision = '73ab6304e68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('number_of_pages', sa.Integer(), nullable=False))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))

    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('podcaster', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('featured_episodes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.drop_column('featured_episodes')
        batch_op.drop_column('podcaster')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('director')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('number_of_pages')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
