"""empty message

Revision ID: ff02fb218600
Revises: 89d93c65a398
Create Date: 2023-05-03 21:44:15.314258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff02fb218600'
down_revision = '89d93c65a398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
